---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: apps/v1
kind: Service
metadata:
  name: nginx-deployment
  labels: 
    app: nginx
spec:
  ports:
  - nodePort: 30777
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
